language: python

python:
  - "2.7"
  - "3.6"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind -y
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=asn1tools setup.py test
  - make test-sdist
  - (cd examples/benchmarks/packages && wget https://github.com/ANSSI-FR/pycrate/archive/master.zip && unzip -qq master.zip)
  - env PYTHONPATH=.:examples/benchmarks/packages/pycrate-master python examples/benchmarks/packages/ber.py
  - env PYTHONPATH=.:examples/benchmarks/packages/pycrate-master python examples/benchmarks/packages/uper.py
  - env PYTHONPATH=. python examples/benchmarks/codecs.py
  - env PYTHONPATH=. python examples/benchmarks/question/question.py
  - env PYTHONPATH=. python examples/hello_world.py
  - env PYTHONPATH=. python examples/x509_pem.py
  - env PYTHONPATH=. python examples/compact_extensions_uper/main.py
  - env PYTHONPATH=. python examples/programming_types/main.py
  - make test-c

after_success:
  coveralls
